-- 不要な_defaults.luaのkeymapをリセットする
pcall(vim.keymap.del,{'n', 'x'}, 'gx')
pcall(vim.keymap.del,'n', 'grn')
pcall(vim.keymap.del,{ 'n', 'x' }, 'gra')
pcall(vim.keymap.del,'n', 'grr')
pcall(vim.keymap.del,'n', 'gri')
pcall(vim.keymap.del,'n', 'grt')
pcall(vim.keymap.del,{ 'x', 'o' }, 'an')
pcall(vim.keymap.del,{ 'x', 'o' }, 'in')
pcall(vim.keymap.del,'n', 'gO')
pcall(vim.keymap.del,{ 'i', 's' }, '<C-S>')
pcall(vim.keymap.del,{ 'i', 's' }, '<Tab>')
pcall(vim.keymap.del,{ 'i', 's' }, '<S-Tab>')
pcall(vim.keymap.del,'n', ']d')
pcall(vim.keymap.del,'n', '[d')
pcall(vim.keymap.del,'n', ']D')
pcall(vim.keymap.del,'n', '[D')
pcall(vim.keymap.del,'n', '<C-W>d')
pcall(vim.keymap.del,'n', '<C-W><C-D>')
pcall(vim.keymap.del,'n', '[q')
pcall(vim.keymap.del,'n', ']q')
pcall(vim.keymap.del,'n', '[Q')
pcall(vim.keymap.del,'n', ']Q')
pcall(vim.keymap.del,'n', '[<C-Q>')
pcall(vim.keymap.del,'n', ']<C-Q>')
pcall(vim.keymap.del,'n', '[l')
pcall(vim.keymap.del,'n', ']l')
pcall(vim.keymap.del,'n', '[L')
pcall(vim.keymap.del,'n', ']L')
pcall(vim.keymap.del,'n', '[<C-L>')
pcall(vim.keymap.del,'n', ']<C-L>')
pcall(vim.keymap.del,'n', '[a')
pcall(vim.keymap.del,'n', ']a')
pcall(vim.keymap.del,'n', '[A')
pcall(vim.keymap.del,'n', ']A')
pcall(vim.keymap.del,'n', '[t')
pcall(vim.keymap.del,'n', ']t')
pcall(vim.keymap.del,'n', '[T')
pcall(vim.keymap.del,'n', ']T')
pcall(vim.keymap.del,'n', '[<C-T>')
pcall(vim.keymap.del,'n', ']<C-T>')
pcall(vim.keymap.del,'n', '[b')
pcall(vim.keymap.del,'n', ']b')
pcall(vim.keymap.del,'n', '[B')
pcall(vim.keymap.del,'n', ']B')
pcall(vim.keymap.del,'n', '[<Space>')
pcall(vim.keymap.del,'n', ']<Space>')
